BeReadyProject/BeReady/urls.py
from django.urls import path
from . import views

app_name = "BeReady"

urlpatterns = [
    path("", views.home, name="home"),
    path("BeReady/About", views.about, name="about"),
    path("BeReady/Contact", views.contact, name="contact"),
    
    path("HR/", views.view_hr, name="view_hr"),
    path("Profile/", views.profile, name="profile"),
    path("HR/Profile/<int:user_id>/", views.HR_detail, name="HR_detail"),
    path("comment/<user_id>/", views.add_comment, name="comment"),

    path("HR/Profile/update/<int:user_id>/", views.update_profile, name="update"),

    path("HR/<int:user_id>/appointment/", views.appointment, name="appointment"), 
    path("add/appointment/<int:user_id>/", views.add_appointment, name="add_appointment"),

]

BeReadyProject/BeReadyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('BeReady.urls')),
    path('accounts/',include('accounts.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

BeReadyProject/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("HRRegister/", views.register_human_resource, name="hr_register"),
]

BeReadyProject/BeReady/models.py
from django.db import models
from accounts.models import HumanResourceProfile
from django.contrib.auth.models import User

# Create your models here.

class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    HR = models.ForeignKey(HumanResourceProfile, on_delete = models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
   

class Appointment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    HR = models.ForeignKey(HumanResourceProfile, on_delete = models.CASCADE)
    desceiption = models.TextField()
    appointment_datetime = models.DateTimeField()

BeReadyProject/BeReady/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from accounts.models import HumanResourceProfile, User
from .models import Comment, Appointment
# Create your views here.

def home(request:HttpRequest):
    '''function to view the home page '''

    return render(request, "BeReady/base.html")


def update_profile(request:HttpRequest, user_id:int):
    '''function to update HR profile'''
    try:
        HR = User.objects.get(id=user_id)
    except:
        return render(request , "blogApp/not_found.html")

    if request.method == "POST":
        HR.first_name = request.POST.get("first_name")
        HR.last_name = request.POST.get("last_name")
        HR.username = request.POST.get("username")
        HR.email = request.POST.get("email")
        HR.password = request.POST.get("password")
        HR.price = request.POST.get("price")
        HR.card_number = request.POST.get("card_number")
        HR.desceiption = request.POST.get("desceiption")
        HR.image = request.POST.get("image")
        HR.save()

        return redirect("BeReady:view_hr")

    return render(request, "BeReady/update_profile.html",{"HR" : HR})


def profile(request:HttpRequest):
    '''function to view HR profile'''
    try:
        user_id : User = request.user.id
        HR = User.objects.get(id=user_id)
        HR_profile = HumanResourceProfile.objects.get(user_id=user_id)
        appointments = Appointment.objects.filter(HR = HR_profile)
    except:
         return render(request ,"BeReady/not_found.html")
        
    return render(request, "BeReady/HR_profile.html",{ "HR":HR,'appointments':appointments})


def view_hr(request:HttpRequest):
    '''function to view all human resources'''
    if "search" in request.GET:
        HRs = User.objects.filter(first_name__contains=request.GET["search"]) 
    else:
        HRs = User.objects.filter(humanresourceprofile__group="HR")

    return render(request, "BeReady/view_hr.html", {"HRs" : HRs})

    
def HR_detail(request:HttpRequest, user_id : int):
    '''function to view the human resources profile  '''
    try:
        HR = User.objects.get(id=user_id)
        HR_profile = HumanResourceProfile.objects.get(user_id=user_id)
        comments = Comment.objects.filter(HR = HR_profile)
    except:
        return render(request ,"BeReady/not_found.html")
 
    return render(request, "BeReady/HR_detail.html", {"HR" : HR,"comments":comments})


def add_comment(request: HttpRequest, user_id : int):
    '''function to make the user add comment on The human resources'''

    try:
        HR = User.objects.get(id=user_id)
        user : User = request.user
    except:
        return render(request , "BeReady/not_found.html")

    if not (user.is_authenticated):
        return redirect("accounts:login_user")

    if request.method == "POST":
        new_comment = Comment(HR=HR.humanresourceprofile,user=user,content=request.POST["content"])
        new_comment.save()

    return redirect("BeReady:HR_detail", HR.id)


def appointment(request:HttpRequest, user_id : int):
    '''function to view the appoinment page'''

    try:
        HR = User.objects.get(id=user_id)
    except:
        return render(request , "BeReady/not_found.html")

    return render(request, "BeReady/appointment.html",{'HR': HR})


def add_appointment(request: HttpRequest, user_id : int):
    '''function to make the user add comment on The human resources'''
    
    '''
    appointments = Appointment.objects.filter(HR = HR_profile)
            previous_appointments : list = []
            for appoinment in appointments:
                print("#######################",appoinment.appointment_datetime)
                previous_appointments.append(appoinment.appointment_datetime)
            print("#######################",previous_appointments)
            print("@@@@@@@@@@@@@@@@@@@@@@@",new_appointment.appointment_datetime)
    '''
    try:
        HR = User.objects.get(id=user_id)
        user : User = request.user

    except:
        return render(request , "BeReady/not_found.html")

    if not (user.is_authenticated):
        return redirect("accounts:login_user")

    if request.method == "POST":
        new_appointment = Appointment(HR=HR.humanresourceprofile,user=user,desceiption=request.POST.get("desceiption"),appointment_datetime=request.POST.get("appointment_datetime"))
        new_appointment.save()

    return redirect("BeReady:HR_detail", HR.id)


def about(request:HttpRequest):
    '''function to view the about page '''

    return render(request, "BeReady/about.html")


def contact(request:HttpRequest):
    '''function to view the contact page '''

    return render(request, "BeReady/contact.html")

BeReadyProject/BeReady/templates/BeReady/HR_detail.html
{% extends 'BeReady/base.html' %}

{% block title %} {{ HR.first_name }} {% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <img width="180px" height="180px" src="{{ HRp.image.url }}"  class="rounded-circle"/>
    </div>
    <div class="col">
      <h2>{{ HR.first_name }} {{ HR.last_name }}</h2>
      <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted me-2 bi bi-linkedin" viewBox="0 0 16 16">
          <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
        </svg></a>
      <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted bi bi-twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </svg></a>
      <p class="mt-2">Session Cost: {{ HR.humanresourceprofile.price }} SR</p>
    </div>
    <div class="col">
    </div>
  </div>

  <div class="row">
    <div class="col-9">
    </div>
    <div class="col-3">
      <a href="{% url 'BeReady:appointment' HR.id %}" class="btn mb-2 btn-outline-secondary">Appointment Booking</a>
    </div>
  </div>

  <hr/>
  <p>Bio</p>
  <p>{{ HR.humanresourceprofile.desceiption }}</p>
  <hr/>

  <p>Comments</p>
  {% for comment in comments %}
      <div class="border rounded-4 p-3 mt-2">
        <span>{{ comment.user.username }}</span>
        <hr>
        <p>{{ comment.content }}</p>
      </div>
  {% endfor %} 
  <form action="{% url 'BeReady:comment' HR.id %}" method="POST">
    {% csrf_token %}
    <hr/>
    <p class="mt-2">Comment</p>
    <textarea name="content" class="form-control"></textarea>
    <input type="submit" class="btn btn-outline-secondary mt-3" value="Add Comment"/>
  </form>
</div>
{% endblock %}

{% block footer %}

{% endblock %}

BeReadyProject/BeReady/templates/BeReady/HR_profile.html
{% extends 'BeReady/base.html' %}

{% block title %} {{ HR.first_name }} {% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <img width="180px" height="180px" src="{{ HRp.image.url }}"  class="rounded-circle"/>
    </div>
    <div class="col">
      <h2>{{ HR.first_name }} {{ HR.last_name }}</h2>
      <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted me-2 bi bi-linkedin" viewBox="0 0 16 16">
          <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
        </svg></a>
      <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted bi bi-twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </svg></a>
      <p class="mt-2">Session Cost: {{ HR.humanresourceprofile.price }} SR</p>
    </div>
    <div class="col">
    </div>
  </div>

  <div class="row">
    <div class="col-10">
    </div>
    <div class="col-2">
      <a href="{% url 'BeReady:update' HR.id %}" class="btn mb-2 btn-outline-secondary">Update Profile</a>
    </div>
  </div>

  <hr/>
  <p>Bio</p>
  <p>{{ HR.humanresourceprofile.desceiption }}</p>
  <hr/>

  <p>Appointments</p>
    {% for appointment in appointments %}
  <div class="border rounded-4 p-3 mt-4">
    <div class="row align-items-start">
      <div class="col-10">
        <span>{{appointment.user.first_name}} {{appointment.user.last_name}}</span>
      <div>
        <small class="text-muted">{{appointment.appointment_datetime}}</small>
      </div> 
      </div>
      <div class="col-2">
        <a href="mailto: {{ appointment.user.email }}" class="btn mt-3 btn-outline-secondary">Send Email</a>
      </div>
    </div>
    <hr>
    <p>{{appointment.desceiption}}</p>
  </div>
  {% endfor %}
</div>
  
{% endblock %}

BeReadyProject/BeReady/templates/BeReady/about.html
{% extends 'BeReady/base.html' %}

{% block content %}
<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                 <img src="https://www.freedomfinance.co.uk/wp-content/uploads/2021/11/1080-x-1080_Careers-1024x1024.png"
                  class="img-fluid" alt="Sample image">
             </div>

             <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <h3 class="text-center"><b>About us</b></h3>
                <hr class="p-2">
 
             <div class="form-outline mb-4">
                <div class="text-center">
                    <h4><strong>Saud Alotaibi</strong></h4>
                    <p></p>
                    

                </div>
                <div class="form-outline mb-4">
                    <div>
                        <p>Website built by a Student in <b>TUWAIQ Academy</b> Python and Web development Bootcamp for final project
                            to help people to be ready for interviews</p>
                    </div>
                    <div class="text-center ">
                    
                        <a href=""><i class="fa fa-envelope p-2" style="font-size:24px"></i></a>
                        <a href=""><i class="fa fa-linkedin p-2"  style="font-size:24px"></i></a>
                        <a href=""><i class="fa fa-github p-2"  style="font-size:24px"></i></a>
                    
                    </div>
                <hr>
                
              </div>
        </div>
    </div>
{% endblock %}

BeReadyProject/BeReady/templates/BeReady/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} Be Ready {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
  <body>
    {% block navbar %}
    <nav class="shadow-sm navbar navbar-expand-lg bg-white mb-4 border-bottom">
      <div class="container-fluid">

        <div class="dropdown me-3">
          <svg xmlns="http://www.w3.org/2000/svg" type="button" data-bs-toggle="dropdown" width="32" height="32" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
          {% if user.humanresourceprofile %}
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'BeReady:profile' %}">Profile</a></li>
          </ul>
          {% endif %}
        </div>
       
        <a class="navbar-brand" href="/">BeReady</a>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'BeReady:view_hr' %}">HR</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'BeReady:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'BeReady:contact' %}">Contact</a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout_user'%}" class="btn btn-outline-secondary">Logout</a>
          {% else %}
            <a href="{% url 'accounts:login_user'%}" class="me-2 btn btn-outline-secondary">Login</a>
          {% endif %}
        </div>
      </div>
    </nav> 
    {% endblock %}

    {% block content %}
    <div class="mt-5 container">
        <div class="row">
          <div class="col">
            <br><br>
            <h2>Be Ready</h2>
            <h3>Will Help You To Be Ready To Your interview</h3>
            <a href="{% url 'BeReady:view_hr' %}" class="me-2 btn btn-lg btn-outline-secondary">View HR</a>
          </div>
          <div class="col">
            <img class="w-100" src="{% static 'images/hero.jpg' %}" class="img-fluid" alt="..."> 
          </div>
        </div>
    </div>
    <div class="bg-light">
      <div class="mt-5 mb-3 p-3 container text-center">
        <div class="row">
          <div class="col">
          </div>
          <div class="col me-5">
            <div class="card rounded-3" style="width: 18rem;">
                <img src="{% static 'images/user_image.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">User</h5>
                  <p class="card-text">Sign In As A User And Find A Human Resource To Help You To Be Ready for Your Interview</p>
                  <a href="{% url 'accounts:register_user'%}" class="btn btn-outline-secondary">Create Account</a>
                </div>
            </div>
          </div>
          <div class="col">
            <div class="card rounded-3" style="width: 18rem;">
                <img src="{% static 'images/HR_image.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Human Resource</h5>
                  <p class="card-text">Sign In As A Human Resource And Help Pepole To Get A Job</p><br>
                  <a href="{% url 'accounts:hr_register'%}" class="btn btn-outline-secondary">Create Account</a>
                </div>
            </div>
          </div>
          <div class="col">
          </div> 
    </div>
    </div>
    {% endblock %}
        
    {% block footer %}   
    <footer class="container-md d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2022 BeReady</span>
        </div>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted me-2 bi bi-twitter" viewBox="0 0 16 16">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="text-muted me-2 bi bi-instagram" viewBox="0 0 16 16">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </svg>
        </ul>
      </footer>
      {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

BeReadyProject/BeReady/templates/BeReady/not_found.html
{% extends 'BeReady/base.html' %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Not Found {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}

    <div class="container text-center font-monospace text-center mt-5 mb-3 p-3">
      <h1>404 | Page Not Found</h1>
      <p>Woops, Looks like this page doesn't exist</p>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br>

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

BeReadyProject/BeReady/templates/BeReady/profile.html
{% extends 'BeReady/base.html' %}

{% block title %} {{ HR.first_name }} {% endblock %}

{% block content %}
<div class="container">
  <div class="row align-items-start">
    <div class="col">
      <img style="width: 150px; border-radius:10%;" src="{{ HRp.image.url }}"  class=""/>
    </div>
    <div class="col">
      <p><b>Desceiption:</b></p>
      <p>{{ HRp.desceiption }}</p>
    </div>
    <div class="col">
  </div>

  <div class="row align-items-center">
    <div class="col mt-3">
      <p><b>{{ HR.first_name }} {{ HR.last_name }}</b></p>
    </div>
  </div>

  <div class="row align-items-start">
    <div class="col">
      <small class="text-muted"><p>Cost By Hour :{{ HRp.price }}</p></small>
    </div>
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
      <a href="{% url 'BeReady:appointment' HR.id %}" class="btn mb-2 btn-outline-secondary">Appointment Booking</a>
    </div>
  </div>
  <hr>
</div>


<div class="container">

  <h2>Comments</h2>


  {% for comment in comments %}
      <div class="border rounded-4 p-3 mt-2">
        <span>{{ comment.user.username }}</span>
        <hr>
        <p>{{ comment.content }}</p>
      </div>
  {% endfor %}
  
  <hr/>
  <form action="{% url 'BeReady:comment' HR.id %}" method="POST">
      {% csrf_token %}
      <label class="form-label"><b>Comment:</b></label>
      <textarea name="content" class="form-control"></textarea>
      <input type="submit" class="btn btn-outline-secondary mt-3" value="Add Comment" />
  </form>

</div>


{% endblock %}

{% block footer %}

{% endblock %}