BeReadyProject/BeReady/urls.py
from django.urls import path
from . import views

app_name = "BeReady"

urlpatterns = [
    path("", views.home, name="home"),
    path("BeReady/About", views.about, name="about"),
    path("BeReady/Contact", views.contact, name="contact"),
    
    path("HR/", views.view_hr, name="view_hr"),
    path("Profile/", views.profile, name="profile"),
    path("HR/Profile/<int:user_id>/", views.HR_detail, name="HR_detail"),
    path("comment/<user_id>/", views.add_comment, name="comment"),

    path("HR/Profile/update/<int:user_id>/", views.update_profile, name="update"),

    path("HR/<int:user_id>/appointment/", views.appointment, name="appointment"), 
    path("add/appointment/<int:user_id>/", views.add_appointment, name="add_appointment"),

]

BeReadyProject/BeReadyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('BeReady.urls')),
    path('accounts/',include('accounts.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

BeReadyProject/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("HRRegister/", views.register_human_resource, name="hr_register"),
]

BeReadyProject/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Creating a Human Resource profile for the user
class HumanResourceProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key=True)
    desceiption = models.TextField()
    group = models.CharField(max_length=32)
    price = models.CharField(max_length=32)
    card_number = models.CharField(max_length=32)
    image = models.ImageField(upload_to="images/")

BeReadyProject/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import HumanResourceProfile 

# Create your views here.

def register_user(request : HttpRequest):
    '''function to create a new user'''

    if request.method == "POST":

        new_user = User.objects.create_user(first_name=request.POST.get('first_name'),last_name=request.POST.get('last_name'),username=request.POST.get('username'), email=request.POST.get('email'), password=request.POST.get('password'))
        new_user.save()
        return redirect("BeReady:home")
        
    return render(request, "accounts/register.html")
    

def register_human_resource(request : HttpRequest):
    '''function to create a new human resource user'''

    if request.method == "POST":

        new_hr = User.objects.create_user(first_name=request.POST.get('first_name'),last_name=request.POST.get('last_name'),username=request.POST.get('username'), email=request.POST.get('email'), password=request.POST.get('password'))
        new_hr.save()

        hr_profile = HumanResourceProfile(user=new_hr, group="HR", desceiption=request.POST.get('desceiption'),price=request.POST.get('price'),card_number=request.POST.get('card_number'),image=request.FILES.get('image', 'default.jfif'))
        hr_profile.save()
        return redirect("BeReady:home")
        
    return render(request, "accounts/hr_register.html")


def login_user(request : HttpRequest):
    '''function to login a user'''

    massage: str = ""
    
    if request.method == "POST":
        user = authenticate(request, username=request.POST.get("username"), password=request.POST.get("password"))
        
        if user:
            login(request, user)
            return redirect("BeReady:home")
        else:
            massage = "User Not Found, Check Your Credentials"

    return render(request, "accounts/login.html", {"msg" : massage})


def logout_user(request: HttpRequest):
    '''function to logout a user'''

    logout(request)

    return redirect("BeReady:home")

    

BeReadyProject/accounts/templates/accounts/hr_register.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HR Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <div class="bg-light mt-5 container border rounded-3 w-50">
      <h1 class="mt-2">Register New HR</h1>
      <form action="{% url 'accounts:hr_register' %}" method="POST" class="d-flex flex-column gap-3" enctype="multipart/form-data">
         {% csrf_token %}
        <div class="container">

          <div class=" mt-3 row align-items-start">
            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">First Name:</label>
                <input name = 'first_name' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>   
            </div>

            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Last Name:</label>
                <input name = 'last_name' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>
          </div>

          <div class="row align-items-start">
            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">User Name:</label>
                <input name = 'username' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>

            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Email:</label>
                <input name = 'email' type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
              </div>
            </div>
          </div>
  
            <div class="row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Password:</label>
                  <input name = 'password' type="password" class="form-control" id="exampleFormControlInput1" placeholder="">
                </div>
              </div>
  
           
            </div>

            <div class="mb-3 row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="formFile" class="form-label">Charge Be Hour:</label>
                  <input type="text" name="price" accept="image/*" class="form-control" />
                </div>
              </div>

              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Card Number:</label>
                  <input name='card_number' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
                </div>
              </div>
            </div>
            
            <div class="row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="exampleFormControlTextarea1" class="form-label">Description:</label>
                  <textarea name="desceiption" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
              </div>
            </div>
            <div class="mb-3 row align-items-start">
              <div class="col">
                <div class="mb-3">
                  <label for="formFile" class="form-label">Upload Image:</label>
                  <input type="file" name="image" accept="image/*" class="form-control" />
                </div>
              </div>
            </div>
        </div>
        <button class="m-2 btn btn-lg btn-outline-secondary" type="submit">Sign in</button>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

BeReadyProject/accounts/templates/accounts/login.html
{% extends 'BeReady/base.html' %}

{% block content %}
<div class="bg-light mt-5 container border rounded-3 w-50">
    <h1 class="mt-2">Login</h1>

    <form action="{% url 'accounts:login_user' %}" method="POST" class="d-flex flex-column gap-2">
       {% csrf_token %}
        <div class="m-2 form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="username" name="username">
            <label for="floatingInput">User Name</label>
        </div>

        <div class="m-2 form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
          <label for="floatingPassword">Password</label>
        </div>

        <button class="m-2 mb-3  btn btn-lg btn-outline-secondary" type="submit">Login in</button>
      </form>
</div>
<br><br><br><br><br><br>
{% endblock%}

BeReadyProject/accounts/templates/accounts/register.html
{% extends 'BeReady/base.html' %}

{% block navbar %}
{% endblock %}
{% block content %}
<div class="bg-light mt-5 container border rounded-3 w-50">
    <h2 class="mt-2">Register New User</h2>
    <form action="{% url 'accounts:register_user' %}" method="POST" class="d-flex flex-column gap-3">
       {% csrf_token %}
      <div class="container">

        <div class=" mt-3 row align-items-start">
          <div class="col">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">First Name:</label>
              <input name = 'first_name' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
            </div>   
          </div>

          <div class="col">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Last Name:</label>
              <input name = 'last_name' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
            </div>
          </div>
        </div>

        <div class="row align-items-start">
          <div class="col">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">User Name:</label>
              <input name = 'username' type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
            </div>
          </div>

          <div class="col">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Email:</label>
              <input name = 'email' type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
          </div>
        </div>

          <div class="row align-items-start">
            <div class="col">
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Password:</label>
                <input name = 'password' type="password" class="form-control" id="exampleFormControlInput1" placeholder="">
              </div>
            </div>
          </div>
      </div>
      <button class="m-2 mb-3 btn btn-lg btn-outline-secondary" type="submit">Sign in</button>
{% endblock %}

{% block footer %}

{% endblock %}